import { BiQuestionMark } from "react-icons/bi";

const ICON_SIZE = "30";
export const CareerLists = [
  {
    position: "SDE Intern",
    company: "Caravel Labs",
    logo: "/caravellabs_logo.jpeg",
    location: "Seattle, Washington",
    location_type: "Hybrid",
    type: "Internship",
    start_date: "2024-09",
    end_date: null,
    industry: "Software",
    
  },
  {
    position: "Problem Solver",
    company: "Physics Wallah",
    logo: "/Physics_wallah_logo.jpg",
    location: "Kolkata,IN",
    location_type: "Regular",
    type: "Fulltime",
    start_date: "2024-05",
    end_date: null,
    industry: "Education",
    // link: "https://tmint.co/",
  },
  {
    position: "Software developer",
    company: "SailBoat IT Sol",
    logo: "/images.jpeg",
    location: "Mumbai, IN",
    location_type: "Onsite",
    type: "Intern",
    start_date: "2023-05",
    end_date: "2023-09",
    industry: "wellness",
    // link: "https://www.mejakita.com/",
  },
  {
    position: "Project Lead (Full stack Dev)",
    company: "IEM-IEDC",
    logo: "/iem1.jpeg",
    location: "Kolkata, IN",
    location_type: "Onsite",
    type: "Intern",
    start_date: "2022-05",
    end_date: "2023-01",
    industry: "wellness",
    // link: "https://www.mejakita.com/",
  },
  {
    position: "Science Tutor",
    company: "Edook",
    logo: "/edook.png",
    location: "Kolkata, IN",
    location_type: "Onsite",
    type: "Full Time",
    start_date: "2021-10",
    end_date: "2024-02",
    industry: "wellness",
    // link: "https://www.mejakita.com/",
  },
  {
    position: "Content Writer",
    company: "Code Dammn",
    logo: "/codedamn.png",
    location: "Remote",
    location_type: "Onsite",
    type: "Full Time",
    start_date: "2021-11",
    end_date: "2022-06",
    industry: "wellness",
    // link: "https://www.mejakita.com/",
  },
  {
    position: "Educator (Future Adda)",
    company: "Youtube",
    logo: "/youtube.png",
    location: "Remote",
    location_type: "Onsite",
    type: "Full Time",
    start_date: "2018-11",
    end_date: "2021-06",
    industry: "wellness",
    // link: "https://www.mejakita.com/",
  },
];
